shyamtawli/devFind

src/data/Profile.json

@shyamtawli , just saw your open source project dev find. It's an osm start to journey happy to contribute tho this project.
I have submitted a pull request to contribute to be the part of journey.

profile-added

---

src/data/Profile.json

Added my profile in devFind\src\data\Profile.json

Added my profile in Profile.json

---

.github/workflows/JSONchecker.yml

solved #12
- Added JSON checker gh action to check JSON code

ci: added JSONchecker.yml #12

---

.github/dependabot.yml

solved #13 
- Added dependabot gh action. It will update all gh actions & npm dependencies if there are any updates needed

ci: added dependabot.yml #13

---

src/data/Profile.json

Profile addition: Jay Kumar Gupta added

---

CODE_OF_CONDUCT.md

Hey there,
I found that the code of conduct file was missing. So I added it.
Thank you!

added the code of conduct

---

CONTRIBUTING.md

Hey there,
I just saw that the contribution guide was missing. So I added it. It will help the contributors to easily contribute into it.
Thank you!

added the contribution guide in the repository

---

src/data/Profile.json

This PR adds my profile onto src/data/Profile.json.

Add: AndreJorgeLopes

---

src/data/Profile.json

Added myprofile

---

src/data/Profile.json

Heyy !! it's my first open-source contribution thanks to you ✌️.

Add profile

---

src/data/Profile.json

added my profile. a small contribution to this repo. In future, I would love to raise more PRs. thanks

added profile of 1010nishant

---

src/data/Profile.json

I have added my data to the profile. JSON file
I just added my details like my name, skills, and my social links to the profile file in the data folder

add: Mandanraj0519

---

src/data/Profile.json

Revert "add: CodeMode365"

---

src/data/Profile.json

Add profile walterowisk

---

src/data/Profile.json

add: prolaxu (Laxman Adhikari )

---

src/data/Profile.json

add: Kartik Pal

---

src/data/Profile.json

add: devhabib429

---

.github/pull_request_template.md

Fixed the `Contributions Guidelines` Link

fix: link in pr template

---

src/data/Profile.json

add: Samrat Ghosh

---

src/data/Profile.json

updated `profile.json` with my profile
added my profile to `profile.json` in `src/data`

add: pranshuj73

---

src/data/Profile.json

data: add priyankarpal

---

src/data/Profile.json

add: Kshitiz Rana

---

src/data/Profile.json

This is my first contribution in OpenSource project . add my profile . 
just update my Profile.json file

shivam-singh

---

src/data/Profile.json

- Add brandeddavid profile.
- Uniformly format `profile.json` data file.

add brandeddavid profile

---

src/data/Profile.json

I've made changes in the src/data/Profile.json file to add my profile data and links
As I'm new to contributions, I don't know enough about the issues that can occur, I just have made changes in data regarding my profile 
Changes that I've made in code of Profile.json file - 
{
"name": "Vinay Chaudhary",
"location": "Delhi",
"bio": "Building Frontend UIs that can handle APIs - ReactJs and Tailwind 💻 - Learning Web Designing 🎨",
"avatar": "https://github.com/vinaysingh-chaudhary.png",
"portfolio": "https://github.com/vinaysingh-chaudhary",
"skills": ["ReactJs", "TailwindCSS", "Javascript", "Web Designing", "Figma", "Java"],
"social": {
"GitHub": "https://github.com/vinaysingh-chaudhary",
"Twitter": "https://twitter.com/Viisactive",
"LinkedIn": …

add: Vinay Chaudhary

---

src/data/Profile.json

add: Muhammad Noorani

---

src/data/Profile.json

add: AseanK

---

src/data/Profile.json

feat: add Priyansh Prajapat

---

src/data/Profile.json

add: runday198

---

src/data/Profile.json

add: Hendrik Bruss

---

src/data/Profile.json

Doing my first contribution by adding profile in devfind

add: Aman Raj

---

src/data/Profile.json

Added Dev Profile to bottom of JSON

add profile: njackman

---

src/data/Profile.json

- fixing typo in oyepriyansh (my profile) description

fix: typo fixing

---

src/data/Profile.json

add: abdur rehman

---

src/data/Profile.json

Created Matt Jarrett in Profile.json

add: Matt Jarrett

---

src/data/Profile.json

I added myself to the list of contributors. You'll notice that my local prettier settings did some changes too, resulting in nicer formatting of `Profile.json` file.

add: jovan6jovan

---

src/data/Profile.json

add: Bryan King Pecho

---

src/data/Profile.json

add: lokytech5

---

src/data/Profile.json

add: Guchu Kelvin

---

src/data/Profile.json

I have added my profile to the json file.
#153

add: Giri Madhan

---

src/data/Profile.json

[I have added  my profile data to the project ]

add: Love Gupta

---

src/data/Profile.json

added my profile in src/data/Profile.json file
Added my profile in Profile.jaon file

add: usama-bagwan

---

src/data/Profile.json

added my profile in src/data/Profile.json file

add: kwansing

---

src/data/Profile.json

this is my first open source contribution

add: Aayushmaan Soni

---

src/data/Profile.json

This could be my first open source contribution.
I added my profile to the json file and when I saved the file, it gave the rest of the profiles better indentation and structure, I didn't mean to do that.

add: Kiran Dev

---

src/data/Profile.json

Added my profile information to data/Profile.json

add: Shauna Empringham

---

src/data/Profile.json

I have added my profile data to the  json file.

add: sonika

---

src/data/Profile.json

add: Abdul Waheed's profile

---

src/data/Profile.json

add: Akshaybagai52

---

src/data/Profile.json

I have added my profile in the profile.json

add: Navneet Kumar Singh

---

src/data/Profile.json

added my Profile info
Added name and skill and profile links
- [# ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [ #] All new and existing tests passed.
- [ #] I have updated the documentation to reflect the changes I've made.
- [ #] My code follows the code style of this project.
- [# ] The title of my pull request is a short description of the requested changes.

add: jaskaran Kamboj

---

src/data/Profile.json

Added Profile: Nsikak Thomas
#180 

add: Nsikak Thomas

---

src/data/Profile.json

add: Lionel Guaregua

---

src/data/Profile.json

Details added on Profile.json file.

add: Aayush Kumar Jha

---

src/data/Profile.json

Profile details added to ```Profile.json``` file.
```
{
"name": "Hirdesh Kumar",
"location": "Agra, UP India",
"bio": "A Full Stack developer with mastery in developing MERN stack applications. Have developed apps for almost all domains",
"avatar": "https://github.com/hirru.png",
"portfolio": "https://github.com/hirru",
"skills": ["Javascript", "ReactJS", "NextJS", "NodeJS", "HTML", "CSS"],
"social": {
"GitHub": "https://github.com/hirru",
"Twitter": "https://twitter.com/hirdesY",
"LinkedIn": "https://www.linkedin.com/in/hirdesh-kumar-498498118/"
}
},
```

Add: Hirdesh Kumar

---

README.md

Added pnpm installation instructions, updated prerequisites and Readme content.
Fixes #191
In this commit, the following changes have been made:
Added installation instructions for pnpm, a package manager used in the project.
Updated the prerequisites section to include pnpm as a requirement.
Included detailed instructions in the Readme file on how to install pnpm and use it to install project dependencies.
Ensured a seamless flow of the Readme content by integrating the pnpm installation instructions without disrupting the existing information.
These changes aim to provide clear instructions for users to install project dependencies using pnpm, catering to both beginners and experienced developers.

Update Readme with pnpm installation instructions and prerequisites

---

src/data/Profile.json

add: B2prakash

---

src/data/Profile.json

Update my profile

---

src/data/Profile.json

Reverts shyamtawli/devFind#195

Revert "Update my profile"

---

public/data/sidsaurav.json
src/ProfilesList.json

add: siddharth saurav

---

public/data/CameronSquires.json
src/ProfilesList.json

Added Cameron Squires to profiles

add: Cameron Squires

---

public/data/bharathkalyans.json
src/ProfilesList.json

* Added my profile to Profile.json.
* Added the following
```
{
"name": "Bharath Kalyan S",
"location": "Bengaluru, India 🇮🇳",
"bio": "Full Stack Developer with expertise in MERN + Spring Boot",
"avatar": "https://github.com/bharathkalyans.png",
"portfolio": "https://showwcase.com/bharathkalyans",
"skills": [
"React JS",
"Next JS",
"Node JS",
"Express JS",
"PostgreSQL",
"MongoDB",
"Java",
"Spring Boot",
"REST APIs",
"Git",
"Tailwind CSS",
"Blockchain",
"Web3",
"Kotlin",
"Android Development",
"Python",
"Machine Learning"
],
"social": {
"GitHub": "https://github.com/bharathkalyans",
"Twitter": "https://twitter.com/bharathkalyans",
"LinkedIn": "https://www.linkedin.com/in/bharathkalyans"
}
}
```

add: Bharath Kalyan S

---

public/data/07prajwal2000.json
src/ProfilesList.json

Added my profile to Profile.json
Added the following
```
{
"name": "Prajwal Aradhya S K",
"location": "Bengaluru, India 🇮🇳",
"bio": "A developer passionate about building systems for the web 🌐 and also develop games 🎮 in my free time.",
"avatar": "https://pbs.twimg.com/profile_images/1648685423453958144/Xo1C5Phg_400x400.jpg",
"portfolio": "https://prajwalaradhya.live/",
"skills": [
"C#",
"Javascript",
"Typescript",
"Asp.Net Core",
"React",
"Next.Js",
"Unity",
"ServiceNow",
"MySQL",
"MongoDB",
"Docker",
"Git",
"Tailwind CSS",
"REST APIs",
"GraphQL"
],
"social": {
"GitHub": "https://github.com/07prajwal2000",
"Twitter": "https://twitter.com/prajwal200",
"LinkedIn": "https://linkedin.com/in/prajwal-aradhya"
}
}
```

added 07prajwal200 profile

---

public/data/Vidip-Ghosh.json
src/ProfilesList.json

add: Vidip Ghosh

---

.github/workflows/feedback.yml

feat: workflow pr feedback

---

public/data/ankushtripathii.json
src/ProfilesList.json

add: ankushtripathii

---

public/data/poorvijn.json
src/ProfilesList.json

add: Poorvi J Nayak

---

public/data/warlegend24.json
src/ProfilesList.json

adding new profile

---

pnpm-lock.yaml
public/data/nikhill56.json
src/ProfilesList.json

Added new profile.
[#245](https://github.com/shyamtawli/devFind/issues/249) 

add:nikhill56

---

public/data/ayezabashir.json
src/ProfilesList.json

[Added a "ayezabashir.json" file in the public/data folder]
Changed nothing, just added ayezabashir.json file in public/data folder and then in the src, in the file ProfilesList.json, i added my github name then added json extension

add: ayezabashir

---

pnpm-lock.yaml
public/data/Yair-N.json
src/ProfilesList.json

Added Yair-N
No Issue
No change
- [ x] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [ x] All new and existing tests passed.
- [ x] My code follows the code style of this project.
- [ x] The title of my pull request is a short description of the requested changes.
I'll be happy to help as far as i can with any open issue

add: Yair-N

---

public/data/therealtmmy.json
src/ProfilesList.json

add: Oluwatimilehin

---

pnpm-lock.yaml
public/data/RodCato.json
src/ProfilesList.json

Added my profile according to instructions provided.
- [ x] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [ x] All new and existing tests passed.
- [ x] I have updated the documentation to reflect the changes I've made.
- [ x] My code follows the code style of this project.
- [ x] The title of my pull request is a short description of the requested changes.

add: Catalino

---

pnpm-lock.yaml
public/data/AyusGup.json
src/ProfilesList.json

Added AyusGup.json in public/data and also Added AyusGup.json in array of profilelists present in src/ProfilesList.json
Seeking forward to contribute...

add: AyusGup

---

public/data/Praveenkumar.json
src/ProfilesList.json

Added Praveenkumar.json in public/data and also Added Praveenkumar.json in array of profile lists present in src/ProfilesList.json.
#264 
Added Praveenkumar.json in public/data and src/ProfilesList.json.
- [✅] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [✅] All new and existing tests passed.
- [✅] I have updated the documentation to reflect the changes I've made.
- [✅] My code follows the code style of this project.
- [✅] The title of my pull request is a short description of the requested changes.

add: Praveen Kumar

---

public/data/Yvad60.json
public/data/anubhav1206.json
src/ProfilesList.json

Add profile for Ivad Yves HABIMANA
#273 
The file `public/data/anubhav1206.json` mentioned changed in this PR is probably due prettier format pre-commit hook

add: Yvad60

---

public/data/avinashji1302.json
src/ProfilesList.json

add:Avinash

---

public/data/wasifdv.json
src/ProfilesList.json

i add my profile in your project & 2 changes

add: wasif akram

---

pnpm-lock.yaml
public/data/ansisme.json
public/data/avinashji1302.json
src/ProfilesList.json

add: ansisme

---

public/data/KaptainCS3.json
src/ProfilesList.json

add:KaptainCS3

---

public/data/salmanakhtar57.json
src/ProfilesList.json

add: Salman Akhtar

---

public/data/ztest95.json
src/ProfilesList.json

Added profile for ztest95
#292 
-
- [/ ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [ /] All new and existing tests passed.
- [ /] I have updated the documentation to reflect the changes I've made.
- [ /] My code follows the code style of this project.
- [/ ] The title of my pull request is a short description of the requested changes.

add: ztest95

---

public/data/SagarBawanthade.json
src/ProfilesList.json

#292 data: Add Your Profile #292 
Added Profile
Added new file SagarBawanthade.json  in public\data
Saved the ProfileLists.json file with my profile entry.
- [/ ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [/ ] All new and existing tests passed.
- [/ ] I have updated the documentation to reflect the changes I've made.
- [/ ] My code follows the code style of this project.
- [/] The title of my pull request is a short description of the requested changes.
😃

add: SagarBawanthade

---

public/data/vigdisha.json
src/ProfilesList.json

add:dishavig

---

public/data/rawasaditya.json
src/ProfilesList.json

#292
- [/] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [/] All new and existing tests passed.
- [/] I have updated the documentation to reflect the changes I've made.
- [/] My code follows the code style of this project.
- [/] The title of my pull request is a short description of the requested changes.

add: Aditya Rawas

---

public/data/DaniloDO.json
src/ProfilesList.json

Hi there. I'm new to open-source coding and interested in helping, developing new skills, and connecting with people. 
Adding my profile data.
Following the instructions and making the pull request as suggested.

add: Danilo Donado

---

public/data/DaniloDO.json
public/data/rawasaditya.json
public/data/roc102.json
src/ProfilesList.json

add: roc102

---

public/data/AlimurtuzaCodes.json
src/ProfilesList.json

add: AlimurtuzaCodes

---

public/data/RutulPatel007.json
src/ProfilesList.json

I have added my profile to the project as said in README file

add: Rutul Patel

---

public/data/idevkshitij.json
src/ProfilesList.json

Added new dev profile
#308
- Added a new "idevkshitij" json file with profile details.
- Added the new filename in "ProfileList.json" array.

add:Kshitij Shrivastava

---

public/data/charukirti.json
src/ProfilesList.json

add: charukirti

---

src/App.css
src/components/Search/Search.css
src/components/Sidebar/Sidebar.css
src/components/Sidebar/Sidebar.jsx

Improved the design on some elements that gave me trouble when I first visited the app.
N/A
* Added an underline to "Add your profile" to indicate that it's clickable
* Added a hover effect to "Add your profile" to encourage clicking
* Improved the layout on smaller screens; specifically the sidebar and search bar
N/A
N/A

overall design and responsiveness improvements

---

public/data/akkash20.json
src/ProfilesList.json

Profile Added.
#313 
Added My Profile.

add: Akkash20

---

public/data/CaglayanCaliskan.json
src/ProfilesList.json

add: Caglayan Caliskan

---

public/data/robertw8.json
src/ProfilesList.json

[Added profile data to public/data]
[Issue #317 ]
[Added profile data to public/data (robertw8.json) and added data to an array in ProfilesList.json]

add: Robertw8

---

public/data/GeniusSniper.json
src/ProfilesList.json

[Added profile data to public/data]
[Issue #317 ]
[Added profile data to public/data (geniussniper.json) and added data to an array in ProfilesList.json]

add:geniussniper

---

pnpm-lock.yaml
public/data/GeniusSniper.json
public/data/robertw8.json
public/index.html

fix: lint and format

---

public/data/dominikgronkiewicz.json
src/ProfilesList.json

add: Dominik Gronkiewicz

---

public/data/dominikgronkiewicz.json
public/data/r4ghuveer.json
public/index.html
src/ProfilesList.json

Adding my Profile to the **devFind** web application.
data: Add Profile #325 
Added my profile json to public/data & updated src/ProfileList.json with my json file name

add: r4ghuveer #325

---

public/data/nikohoffren.json
src/ProfilesList.json

Added nikohoffren.json file with my information to public/data directory.
Added nikohoffren.json to src/ProfilesList.json file.

add: nikohoffren

---

public/data/Piyush-onGIT.json
src/ProfilesList.json

Added my GitHub profile Piyush-onGIT according to the instructions given in the Readme file.
#325

add: Piyush-onGIT

---

public/data/KaloniGiga.json
src/ProfilesList.json

add: KaloniGiga

---

public/data/eskayML.json
src/ProfilesList.json

add: eskayML 

---

public/data/Anushka-Bhowmick.json
src/ProfilesList.json

I have added my GitHub profile.

add: Anushka-Bhowmick

---

public/data/Anushka-Bhowmick.json
public/data/VanshVg.json
public/data/eskayML.json
src/ProfilesList.json

Added my profile in public/data.
#338
Added my profile in public/data and added that file name in src/ProfileList.json

add:VanshVg

---

public/data/XanderRubio.json
src/ProfilesList.json

I've added my information to be listed on the devFind open-source project!

add: XanderRubio

---

public/data/XanderRubio.json
src/ProfilesList.json

I have found a bug that the profile for  _Ankush tripathi_ Location is not set, also the view profile button is not working
#346
I have replace the `your location` with the users current location according to his GitHub Profile (Maharashtra , India)

Update ankushtripathii.json - Fixing location and profile

---

public/data/stlajay.json
src/ProfilesList.json

add: stlajay

---

public/data/Mannuel25.json
src/ProfilesList.json

add: mannuel25

---

public/data/chazGraham.json
src/ProfilesList.json

Added my profile information to the data folder and added chazGraham.json to Profiles.json in the src folder.
data: Add Profile #338

add: chazgraham

---

public/data/DoonOnthon.json
src/ProfilesList.json

Added my profile to the list.
#338
Just added my name to the list.
- [ x ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [ X ] All new and existing tests passed.
- [ N/A ] I have updated the documentation to reflect the changes I've made.
- [  X ] My code follows the code style of this project.
- [  X ] The title of my pull request is a short description of the requested changes.

add: DoonOnthon

---

public/data/anushatomar13.json
src/ProfilesList.json

add: anushatomar13

---

public/data/hellofaizan.json
src/ProfilesList.json

Just added my profile to the list
Added my profile

add: HelloFaizan

---

public/data/anushatomar13.json
public/data/dpass47.json
public/data/hellofaizan.json
public/index.html
src/ProfilesList.json

Added profile for dpass47.
#364 
Created dpass47.json file to public/data which includes all necessary data for the profile. Also added dpass47 to the src/ProfilesList.json array.
- [x ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [x ] All new and existing tests passed.
- [x ] I have updated the documentation to reflect the changes I've made.
- [x ] My code follows the code style of this project.
- [x ] The title of my pull request is a short description of the requested changes.

add: dpass47

---

public/data/DebadityaSom.json
src/ProfilesList.json

I have added my profile in the JSON folder and also made the necessary changes in the ProfileList.json file

add: Debaditya Som

---

public/data/abdosahsah.json
src/ProfilesList.json

Hi there,
I have followed the steps in the README.md file to add my profile.
This is my first contribution and I will be happy to accept the pull request
Thanks

add: abdosahsah profile

---

public/data/athenacats.json
src/ProfilesList.json

Hi, I have added my developer profile to the project.

add: athenacats

---

public/data/RaghavSaptam.json
src/ProfilesList.json

add:raghav-singh

---

public/data/daimbk.json
src/ProfilesList.json

add: daimbk

---

public/data/JaredCaprio.json
src/ProfilesList.json

add:JaredCaprio

---

public/data/Geekverma.json
public/data/JaredCaprio.json
public/data/RaghavSaptam.json
public/data/RaviSolanki27.json
public/data/daimbk.json
public/index.html
src/components/Search/Search.css

I changed the style of the search bar to be more nicer and correct some issues in responsive 
Issue NO: #383
I deleted from the class ( search-bar ) : 
- width: 31rem;
- In the responsive I deleted the width: 95%
because it will take the full width as default and it was more nicer
then, I added for it :-
- display: flex
- align-items: center
- justify-content: end
All of this to adjust the search icon
And, The search icon I deleted the top and right and I added margin-right: 10px

Refactor Search Bar

---

public/data/arewageek.json
src/ProfilesList.json

add: Austin Ameh

---

public/data/priyanshu0511.json
src/ProfilesList.json

add: Priyanshu Singh

---

public/data/anevski-stefan.json
public/data/arewageek.json
public/data/vamsi-spoidey7.json
src/ProfilesList.json

add: vamsi madugula 

---

public/data/Hraj24.json
src/ProfilesList.json

add: Hraj24

---

public/data/haseebyousuf.json
src/ProfilesList.json

Add  new profile
added haseebyousuf.json in /public/data and then added to profilesList.json

add:haseebyousuf

---

public/data/NextThread.json
src/ProfilesList.json

add: NextThread

---

public/data/Adebayoibrahim.json
public/data/Hraj24.json
public/data/alexpeain.json
public/data/priyanshu0511.json
src/ProfilesList.json

add:alexpeain

---

public/data/Tiensuperman.json
public/data/joshijoe05.json
src/ProfilesList.json

add: joshijoe05

---

public/data/Tiensuperman.json
public/data/surfiniaburger.json
src/ProfilesList.json

add: Adedoyinsola Ogungbesan

---

public/data/Diyouf.json
src/ProfilesList.json

[Thank for , Having a new contribution ]
[Added My profile]

add: Diyouf

---

public/data/vedant-28.json
src/ProfilesList.json

add: vedant-28

---

public/data/kondapalli19.json
src/ProfilesList.json

add:Koyal Kondapalli

---

public/data/Rushikesh_Bhalerao.json
src/ProfilesList.json

Hi @shyamtawli,
I have added a Profile and also started the repo.😊
Please merge my PR, Using the "Hacktoberfest-accepted" tag. Happy developing :)

add: bhaleroa-2002

---

pnpm-lock.yaml
public/data/trdxlucifer.json
src/ProfilesList.json

Created my first Pull Request for contributing and adding my name in json file as per given

add: trdxlucifer

---

public/data/AbhiPatel10.json
src/ProfilesList.json

#411 
Dev profile added
Please add Hacktoberfest label

add: Abhi Patel profile

---

public/data/shresritik.json
src/ProfilesList.json

add: shresritik

---

public/data/afreenpoly.json
src/ProfilesList.json

add:afreenpoly

---

public/data/raunakgiri21.json
src/ProfilesList.json

Added new profile
- changed src/profileList.json
- added public/data/raunakgiri21.json

add: Raunak Giri

---

public/data/Samaresh-Das.json
src/ProfilesList.json

Added my json file to data and also included my profile

add: Samaresh-Das

---

public/data/Emmanuel-Tech-Dev.json
public/data/Rushikesh_Bhalerao.json
src/ProfilesList.json

add:Emmanuel-Tech-Dev

---

public/data/trishan9.json
src/ProfilesList.json

Added my data
[Include any related issues or pull requests that this PR addresses or is related to. Use GitHub's shorthand syntax to link to them, like #411  ]

add: trishan9

---

public/data/pranita28Dane.json
src/ProfilesList.json

add: Pranita Dane

---

src/components/Profile/Profile.jsx
src/components/Search/Search.css

close #415
Removed unwanted code 
Please add Hacktoberfest label

fix: removed unwanted code

---

public/data/RaturiAR7.json
src/ProfilesList.json

add: anshulraturi

---

public/data/Sakshi29G.json
src/App.js
src/ProfilesList.json

add: Sakshi29G

---

public/data/Avishek-shrestha.json
src/ProfilesList.json

add: Avishek-sth

---

public/data/mridul2820.json
src/ProfilesList.json

Added my Profile to devFind
#411 
Added the profile.json and updated it in the list

add: Mridul2820

---

public/data/RaturiAR7.json
public/data/pranita28Dane.json
public/data/raushan.json
public/data/trishan9.json
src/ProfilesList.json
src/components/Profile/Profile.jsx

add-raushan-profile

---

public/data/shivansh0203.json
src/ProfilesList.json

add: shivanshsin0203

---

public/data/digvijaysinghh.json
src/ProfilesList.json

add: digvijaysinghh

---

public/data/RaturiAR7.json
public/data/Shiva-Sai-ssb.json
public/data/linkzy.json
src/ProfilesList.json
src/components/Profile/Profile.css
src/components/Profile/Profile.jsx

add: linkzy

---

public/data/aniimessh.json
src/ProfilesList.json

I have added my profile
there is no related issue
added my profile links

add: aniimessh

---

public/data/Avishek-shrestha.json
public/data/shivansh0203.json
public/data/tedante.json
src/ProfilesList.json

Added tedante profile to devFind
please kindly to reviewing my pull request
thank you
https://github.com/shyamtawli/devFind/issues/411
Added the tedante.json and updated it in the ProfileList.json

add: tedante

---

public/data/vaibhav-009.json
src/ProfilesList.json

I have added my profile.
No related issue.

add : Vaibhav

---

public/data/THE-AryanKumar.json
public/data/aniimessh.json
public/data/digvijaysinghh.json
public/data/shivansh0203.json
src/ProfilesList.json
src/index.css

Added myself on devFind
added my profile card to profilelist.json

add: THE-AryanKumar

---

public/data/destryptor.json
src/ProfilesList.json

Added myself, Sharanya Chakraborty, to the profiles list.

add: Sharanya Chakraborty

---

public/data/Haris-Mohanty.json
src/ProfilesList.json

Add Profile: Haris Mohanty

---

public/data/Sairajepawar.json
src/ProfilesList.json

add: Sairaj Pawar

---

public/data/g0v1ndN.json
src/ProfilesList.json

Adding myself to devFind.
N/A
add: g0v1ndN - Added my details to DevFind.

add: g0v1ndN

---

public/data/biplobsd.json
public/data/vaibhav-009.json
src/ProfilesList.json

Added myself on devFind
Added my profile card to profilelist.json

add: Biplob Sutradhar

---

public/data/nabinbhatt.json
src/ProfilesList.json

I have added my profile on devFind
No related issues
This PR adds my profile into the devFind open source project.

add: Nabin Bhatt

---

public/data/ashish5433.json
public/data/vaibhav-009.json
src/ProfilesList.json

add: Ashish

---

public/data/siddhishah109.json
public/data/vaibhav-009.json
src/ProfilesList.json

add: siddhi shah

---

public/data/devmuhib009.json
src/ProfilesList.json

add: devmuhib009

---

README.md

Add devfind website link in README for easy access

doc : add devFind website link in README

---

public/data/aftabrehan.json
src/ProfilesList.json

add: aftabrehan

---

public/data/sanghdeep.json
src/ProfilesList.json

Added My Profile and related data
- [- ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [- ] All new and existing tests passed.
- [ -] I have updated the documentation to reflect the changes I've made.
- [- ] My code follows the code style of this project.
- [ -] The title of my pull request is a short description of the requested changes.

add: sangdeepganvir

---

public/data/Priyanshu.json
src/ProfilesList.json

add: harshhere

---

public/data/aaadityag.json
src/ProfilesList.json

Adding aaadityag.json to public/data
Updating ProfileList.json

add: AaadityaG

---

public/data/g0v1ndN.json
public/data/hackerspider09.json
src/ProfilesList.json

update profile data with new user json
none
added new user in public data dir

add : hackerspider09

---

public/data/rahul0x00.json
src/ProfilesList.json

add: rahul0x00

---

public/data/AlienMonk.json
public/data/Haris-Mohanty.json
public/data/Sairajepawar.json
public/data/destryptor.json
public/data/leabuende.json
public/data/vaibhav-009.json
src/ProfilesList.json

add: AlienMonk

---

public/data/uozcan12.json
src/ProfilesList.json

add: uozcan12

---

public/data/thenishantsapkota.json
src/ProfilesList.json

add: nishant sapkota

---

src/App.js
src/components/ProfileSkeleton/ProfileSkeleton.css
src/components/ProfileSkeleton/ProfileSkeleton.jsx
src/components/Sidebar/Sidebar.jsx

On homepage where all the profiles are loaded, a profile skeleton loader has been added to show until the profile data loads.
Issue #498 
Created a new skeleton component having similar structure as profile card. Rendering this until the profile data loads.

[STYLE]: Added profile skeleton loader on Homepage

---

public/data/Pratikdate.json
src/ProfilesList.json

Include my profile info.
please add hectoberfest accepted

add  Pratikdate

---

public/data/sneha9231.json
src/ProfilesList.json

This my first pull request for hacktoberfest. Thank you for your clear guidelines. I followed every step and to be honest it was super beginner friendly!! Thank you 3000.

add: sneha9231

---

public/data/mouli-3542.json
src/ProfilesList.json

Added my profile to profile list and also created a json file for it.
Added the following JSON object in the public/data folder:
{
"name": "Chandra Mouli",
"location": "Andhra Pradesh, India",
"bio": "I'm a full-stack developer specializing in the MERN stack, with experience in building scalable and efficient web applications. I have a keen interest in cloud computing. So, I'm learning AWS.",
"avatar": "https://avatars.githubusercontent.com/u/143725284?v=4",
"portfolio": "https://github.com/Mouli-3542",
"skills": ["AWS", "Javascript", "Node.js", "MongoDB", "ReactJS", "Express.js", "HTML", "CSS"],
"social": {
"GitHub": "https://github.com/Mouli-3542",
"Twitter": "https://twitter.com/Mouli3542",
"LinkedIn": "https://www.linkedin.com/in/moulinemana/"
}
}
- [X ] I have read and followed the …

add: mouli-3542

---

README.md

I have added the LICENSE section in the README file with enhanced presentation. Also I have added a MIT logo, license badge and updated text with a cleaner format, including a hyperlink to the LICENSE file.
- #551

chore: updating README with repo LICENSE

---

public/data/Prakhar-Shankar.json
src/ProfilesList.json

add:Prakhar-Shankar

---

public/data/biswabaibhab007.json
src/ProfilesList.json

Added my profile on devFind
I've added my information in json file so that other developers can find me on this site.

add: biswabaibhav007

---

README.md

This PR add the Github badges like `star`, `pullrequest`, `fork` and other in the README
Solve issue #518

Chore: Updated README with Github badges

---

CONTRIBUTING.md

Add a change directory command in CONTRIBUTING.md file

[DOC]: Command to change directory in CONTRIBUTING.md

---

public/data/SoulNikhar.json
src/ProfilesList.json

add: SoulNikhar

---

public/data/TaeMochi12.json
src/ProfilesList.json

add : TaeMochi12

---

public/data/aayush105.json
src/ProfilesList.json

add: aayush105

---

public/data/tholkappiar.json
src/ProfilesList.json

_Added My Profile._
_Added my Profile to the Json List ._

add-profile: tholkappiar

---

public/data/imrtls00.json
src/ProfilesList.json

Also addded it to ProfilesList.json.

add: imrtls00

---

public/data/Namesh2710.json
src/ProfilesList.json

add:Namesh2710

---

public/data/hemu-git-hub.json
src/ProfilesList.json

add: hemu-git-hub 

---

public/data/gayatri-p786.json
src/ProfilesList.json

I have added my profile data json file.

add: gayatri-p786

---

public/data/TechBond7.json
src/ProfilesList.json

Added my profile
- Added the file "TechBond7.json" in the public/data folder.
- Modified the "ProfilesList.json" file in the src directory.

add:TechBond7

---

public/data/sukuasoft.json
src/ProfilesList.json

In this PR I basically added my profile to the project.
This PR is related to issue [679](https://github.com/shyamtawli/devFind/issues/679)
I added the sukuasoft.json file to the project with my information and also added the file name "sukuasoft.json" to the ProfileList.json file

Add: Sebastião Sukuakueche Profile

---

public/data/Edlavio.json
src/ProfilesList.json

add: Edlavio

---

public/data/trp02.json
src/ProfilesList.json

added necessary data for profile in json & profile list
#700

add: trp02

---

public/data/numcys.json
src/ProfilesList.json

add: numcys

---

public/data/armaney.json
src/ProfilesList.json

add: arman ahmed

---

public/data/prkaushal.json
src/ProfilesList.json

add : prashant kaushal

---

public/data/SutanjoyPal.json
public/data/armaney.json
public/data/utkbkts.json
src/ProfilesList.json

add: Sutanjoy Pal

---

public/data/nitesh32.json
src/ProfilesList.json

add: nitesh32

---

public/data/Rakshit-gen.json
src/ProfilesList.json

Just Added my profile in the json format and updated it in the Profile list.

add: Rakshit-gen

---

public/data/0xSaksham.json
src/ProfilesList.json

I just added my name to my Profile and social links.
No Related Issues
Just added my name.
Please merge my PR.

add: Saksham Gupta

---

public/data/shrix1.json
src/ProfilesList.json

- Added `shrix1.json` file 
- Added `shrix1.json` file
- Added `shrix1.json` string in profileJosn array

add: shrix1

---

public/data/anjalbinayak.json
src/ProfilesList.json

I have added my github profile

add: Anjal Binayak Adhikari

---

public/data/VishalIsharani.json
src/ProfilesList.json

add: Vishal Isharani

---

public/data/thasup.json
src/ProfilesList.json

add: thasup

---

public/data/alamin-karno.json
src/ProfilesList.json

I added my profile to the data.
N/A
I have added my profile to the database.
N/A

add: alamin-karno

---

public/data/nandha46.json
src/ProfilesList.json

add:Nandhakumar Subramanian

---

public/data/blmayer.json
src/ProfilesList.json

Added blmayer to the profiles.

add: blmayer

---

public/data/Rakshit-gen.json
public/data/anjalbinayak.json
public/data/furkankapukayaa.json
public/data/nitesh32.json
public/data/rohan-bhautoo.json
src/ProfilesList.json

Added profile to JSON and list

add: rohan-bhautoo

---

public/data/ugbabeOg.json
src/ProfilesList.json

add: Ugbabe Choco

---

public/data/DhanushNehru.json
src/ProfilesList.json

add: DhanushNehru

---

public/data/mateusfg7.json
src/ProfilesList.json

Include [Mateus Felipe](https://mateusf.com) to the database

add: Mateus Felipe Gonçalves

---

public/data/MastooraTurkmen.json
src/ProfilesList.json

add: Mastoora Turkmen

---

public/data/Licodeao.json
src/ProfilesList.json

add: Licodeao

---

public/data/ImtiazNayeemShawon.json
src/ProfilesList.json

add: Imtiaz Nayeem Shawon

---

public/data/apenasgabs.json
src/ProfilesList.json

Add @ApenasGabs profile on profile list

Add: apenasgabs.json

---

public/data/jeremyrayjewell.json
src/ProfilesList.json

Added my details
N/A
- [ x] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [x ] All new and existing tests passed.
- [ x] I have updated the documentation to reflect the changes I've made.
- [ x] My code follows the code style of this project.
- [ x] The title of my pull request is a short description of the requested changes.

add: jeremyrayjewell

---

public/data/carvalholeo.json
src/ProfilesList.json

add: leo carvalho

---

public/data/shagunsharma6677.json
src/ProfilesList.json

I've added my username in src/ProfilesList.json and user details in public/data/shagunsharma6677.json file.

add: Shagun Sharma

---

public/data/AkshayPratapSingh09.json
src/ProfilesList.json

add: AkshayPratapSingh09

---

pnpm-lock.yaml
public/data/bxljoy.json
src/ProfilesList.json

add: bxljoy

---

src/App.js

This pull request resolves an issue with the scroll-to-top functionality on page changes, guaranteeing a consistent user experience. In addition, the profile container now features scrollable functionality. This change attempts to empower users by making it easier to use the search bar and navigation options, even when they are in the middle of a scroll. These enhancements increase general usability and navigation, resulting in a more seamless and intuitive engagement with the application.
Fixes #854
https://github.com/shyamtawli/devFind/assets/97862450/26ffbf51-f1ad-47cc-95f3-acfaf3d77a60

Fixed Scroll to Top Functionalilty

---

public/data/dayvsonspacca.json
src/ProfilesList.json

add: dayvsonspacca

---

public/data/Ivanov1201.json
src/ProfilesList.json

add: Ivanov1201

---

public/data/sahilatahar.json
src/ProfilesList.json

I have added my profile
When I click on `add your profile` button it redirect to GitHub project repo but does not scroll to `Steps to Add Your Profile Data` section in readme.

add: sahilatahar

---

public/data/himanshuchandola.json
src/ProfilesList.json

add: himanshuchandola

---

public/data/iagorivelo.json
src/ProfilesList.json

add: iagorivelo

---

public/data/saras1212.json
src/ProfilesList.json

Added a profile for saras1212
Issue #866 
Created saras1212.json and added it to the ProfilesList
- [ x] All new and existing tests passed.
- [x ] I have updated the documentation to reflect the changes I've made.
- [ x] My code follows the code style of this project.
- [x ] The title of my pull request is a short description of the requested changes.

added profile: saras1212

---

public/data/HlobisileLukhele.json
public/data/JuanPabloDiaz.json
src/ProfilesList.json

#866
Profile Data Added to project by following the contribution guidelines and readme files.

add: JuanPabloDiaz

---

public/data/HlobisileLukhele.json
public/data/euotiniel.json
src/ProfilesList.json

I added my profile to the project with the instructions described in the readme.

add: euotiniel

---

public/data/chelseaqnguyen.json
src/ProfilesList.json

Added chelseaqnguyen.json file to directory public/data and modified ProfilesList.json in the src directory.
I added myself to the ProfilesList.json file.

add: chelseaqnguyen

---

public/data/sanchitbajaj02.json
src/ProfilesList.json

Added the github profile of [Sanchitbajaj02](https://github.com/Sanchitbajaj02) into the list of devFind developers.
Reference issue: #866

add: sanchitbajaj02's profile

---

public/data/swayamvasavada.json
src/ProfilesList.json

I've added new profile as mentioned in readme.md file
Issue #866 
Created swayamvasavada.json and added it to the ProfilesList

add: Swayam Vasavada

---

public/data/manuelbento19.json
src/ProfilesList.json

add: Manuel Bento

---

public/data/Ken-Musau.json
src/ProfilesList.json

add: Ken-Musau

---

bifrost.json
public/data/koushal.json
public/data/manuelbento19.json
public/data/swayamvasavada.json
src/ProfilesList.json

Added my profile information to the `public/data` directory.
None.
- Added a new JSON file with my profile information.
- Updated the `ProfilesList.json` file in the `src` directory to include my profile.
Please review the changes to ensure that my profile information has been correctly added and that it follows the project's guidelines. Thank you

add: Koushal-Anitha-Raja

---

public/data/agtorres3.json
src/ProfilesList.json

I added my dev info and the name of the file in the appropriate areas according to the readme file
I was having issues with making a branch, changes were made in the master, I know this isnt preffered practice. Im sorry
- [x ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [x ] All new and existing tests passed.
- [ x] I have updated the documentation to reflect the changes I've made.
- [x ] My code follows the code style of this project.
- [x ] The title of my pull request is a short description of the requested changes.

add: agtorres3

---

public/data/jinx-vi-0.json
src/ProfilesList.json

- [✓ ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [✓ ] All new and existing tests passed.
- [ ✓] I have updated the documentation to reflect the changes I've made.
- [ ✓] My code follows the code style of this project.
- [✓ ] The title of my pull request is a short description of the requested changes.

Add profile : Adarsh

---

CONTRIBUTING.md
README.md

I have update README.md and CONTRIBUTIONG.md file and make some work easy for developers to add their profile
If you are using react then use [Vite](https://vitejs.dev/). It is more faster than create-react-app. If you are thinking to migrate to to NextJS then don't need to do this.
If you have any work for me. please let me know

Update documentation for pnpm to npm

---

public/data/brianobot.json
src/ProfilesList.json

I added my profile as instructed on the read me of the main repo

add: Brian Obot

---

public/data/brianobot.json
src/App.css

[FIX]: Scrollbar in light mode

---

public/data/Nanditasunil.json
src/ProfilesList.json

Folloing the stpes of Readme.md I've added my details 
--
--
--

add: nanditaSunil

---

public/data/sakshamgupta921.json
src/ProfilesList.json

Added my profile
- [✅ ] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [✅  ] All new and existing tests passed.
- [ ✅ ] I have updated the documentation to reflect the changes I've made.
- [ ✅ ] My code follows the code style of this project.
- [ ✅ ] The title of my pull request is a short description of the requested changes.

add: sakshamgupta912

---

public/data/developer_assets.json
src/ProfilesList.json

add: patrick 

---

public/data/AndresFelipe077.json
public/data/rohitxdd.json
src/ProfilesList.json

The json was created for my user's profile as in the readme instructions
{
"name": "Andrés Felipe Pizo Luligo",
"location": "Colombia - Cauca - Popayán",
"bio": "Young man passionate about software, I love capturing incredible ideas.",
"avatar": "https://github.com/AndresFelipe077.png",
"portfolio": "https://github.com/AndresFelipe077",
"skills": ["Laravel", "Nest.js", "Angular", "Unity"],
"social": {
"GitHub": "https://github.com/AndresFelipe077",
"Twitter": "https://twitter.com/",
"LinkedIn": "https://www.linkedin.com/in/andres-felipe-pizo-luligo-6181001b1"
}
}
"AndresFelipe077.json",
Add my code as in the readme instructions

add: Andres Felipe

---

public/data/pragyakashyap.json
src/ProfilesList.json

add: pragya kashyap

---

public/data/Deep512.json
src/ProfilesList.json

Added profile data for Deep512
And added the JSON file to the profile list
Issue: #938

Added profile for Deep512

---

public/data/Ag-neta.json
src/ProfilesList.json

Add: Ag-neta

---

public/data/astro-dally.json
src/ProfilesList.json

Added profile data for Dally R
And I added the JSON file to the profile list.
Issue: https://github.com/shyamtawli/devFind/issues/938

Added profile for Dally

---

public/data/Keshav-Chaudhary.json
src/ProfilesList.json

**## Description**
Added my profile information to the repository.
**## Related Issues**
#963
**## Changes Proposed**
Added my profile information to the public/data/Keshav-Chaudhary.json file.
Updated the src/ProfilesList.json file 
**## Checklist**
- [✅] I have read and followed the [Contribution Guidelines (https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [✅]  All new and existing tests passed.
- [✅]  I have updated the documentation to reflect the changes I've made.
- [✅]  My code follows the code style of this project.
- [✅]  The title of my pull request is a short description of the requested changes.
**## Note to reviewers**
Please review and provide feedback. Thank you!

added Profile for : Keshav-Chaudhary

---

package-lock.json
public/data/Ag-neta.json
public/data/Deep512.json
public/data/Keshav-Chaudhary.json
public/data/astro-dally.json
public/data/prajwalmandlik2004.json
src/ProfilesList.json

Added My Profile to DevFind
Add new .json file for my profile

add : Prajwal Mandlik

---

public/data/root-0101.json
src/ProfilesList.json

add: rooot-0101

---

public/data/RashidSiddiqui2004.json
src/ProfilesList.json

Updated my profile in the project.
Updated my profile in the project.

add: Rashid Siddiqui

---

package-lock.json
public/data/abhishek732.json
src/ProfilesList.json

add: Abhishek0732

---

src/App.js

@shyamtawli 
[Feat]: Added Pagination #1017
close #1017
i resolve and added pagination in list
- update app

[BUG]: Pagination Not Showing

---

public/data/Sahilll15.json
src/ProfilesList.json

I have created a pull request to add my profile to the website

Sahilll15 Profile

---

public/data/Monalisha-Roy.json
src/ProfilesList.json

Added my profile to the contributors page of the website.
N/A
- added "Monalisha-Roy.json" file in the public/data to add my bio and other details for the website. 
- updated the "Profilelist.json" file. 
N/A
Please verify that my profile appears correctly on the contributors page.

add: Monalisha Roy

---

public/data/BHS-Harish.json
src/ProfilesList.json

add : balaharisankar

---

public/data/connectaryal.json
src/ProfilesList.json

add: Shiva Aryal

---

public/data/tainguyenphat74.json
src/ProfilesList.json

add: tainguyenphat74

---

src/components/Profile/Profile.jsx
src/components/Sidebar/Sidebar.jsx

fixed the profile alignment for tablet size to enhance the user experience.
#1027 
added style for md: size using tailwind and made the component absolute that was creating problem.

Fixed Responsiveness for laptop 1024 and tablet size

---

public/data/giuliarappo.json
src/ProfilesList.json

add: Giulia Rappo

---

public/data/Saipradyumna Goud Chiragoni.json
public/data/boytur.json
src/ProfilesList.json

N/A
- Add my profile
I don't know why when I commit my code then in Chiragoni Sai Pradyumna Goud code gets auto formatted, I try to discard it and make new a commit but the code is still changed.

add: boytur

---

public/data/Saipradyumna Goud Chiragoni.json
public/data/mayurr7.json
src/ProfilesList.json

add: mayurr7

---

public/data/Om-pawarr.json
src/ProfilesList.json

add: Om-pawarr

---

public/data/krtEngineer.json
src/ProfilesList.json

Hello I have added the my Profile in Data section please review

add: kushagra raj tiwari

---

public/data/Jyothishree2k5.json
public/data/ctafsiras.json
src/ProfilesList.json

add: Chowdhury Tafsir Ahmed Siddiki

---

public/data/hamzathul.json
src/ProfilesList.json

Added my profile
No related issues. just added my profile
added my profile

add: Hamzathul Favas E

---

package-lock.json
public/data/adityashah7867.json
public/data/atik-7866.json
src/ProfilesList.json

add: Atik Vohra

---

public/data/vsnikhilvs.json
src/ProfilesList.json

Create vsnikhilvs.json for my profile
- [ +] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [ +] All new and existing tests passed.
- [ +] I have updated the documentation to reflect the changes I've made.
- [+ ] My code follows the code style of this project.
- [+ ] The title of my pull request is a short description of the requested changes.

Create vsnikhilvs.json for my profile

---

public/data/Stoppedwumm.json
src/ProfilesList.json

Add my profile 
None
* Add my profile.json
* Add my profile.json to the profile list

add: Stoppedwumm

---

public/data/hamzathul.json
public/data/krtEngineer.json
public/data/prashantrai-30.json
src/ProfilesList.json

add: prashantrai-30

---

package-lock.json
public/data/Santhosh-G12.json
src/ProfilesList.json

add: SanthoshG12

---

README.md

I just made a few changes to the readme document to update the `Add Your Profile Steps`
#1165 
Just changed the folder from `src` => `components`
- [ x] I have read and followed the [Contribution Guidelines](https://github.com/shyamtawli/devFind/blob/master/CONTRIBUTING.md).
- [x ] I have updated the documentation to reflect the changes I've made.
- [x ] The title of my pull request is a short description of the requested changes.

updated add profile data steps

---

components/ProfileList.json
public/data/berhili098.json

This pull request includes the addition of a new profile to the profile list and the corresponding data file for the new profile.
Profile list update:
* [`components/ProfileList.json`](diffhunk://#diff-a9be64885ba2d111e8f92bdaa5424b3987a6eaf3ee96877639cd7e9ad50f8dadL458-R459): Added "berhili098.json" to the profile list.
New profile data:
* [`public/data/berhili098.json`](diffhunk://#diff-1363bb7b20972ccbc98c31dc1f1a89e4b1604b0bef1325cb6433f55bbbc75bedR1-R15): Added a new data file for the user "Berhili Oussama" with details such as avatar, bio, location, portfolio, skills, and social links.

Pr:Feat Add Profile 
